name: ddh_exchange_flutter
description: 点点换 - 积分兑换与用户易货平台
version: 1.2.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^12.1.1
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  package_info_plus: ^4.2.0
  path_provider: ^2.1.1
  crypto: ^3.0.3
  google_fonts: ^6.1.0
  # Compatibility mode: Comment out native plugin dependencies
  # dio: ^5.3.2
  # flutter_secure_storage: ^9.0.0
  # shared_preferences: ^2.2.2
  # device_info_plus: ^9.1.0
  # image_picker: ^1.0.4
  # share_plus: ^7.2.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
